// <auto-generated />
using System;
using ApiPhoneStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entites.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Samsung brand description",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple brand description",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tecno brand description",
                            Name = "Tecno"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entites.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S1",
                            Price = 800m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S2",
                            Price = 801m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S3",
                            Price = 802m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S4",
                            Price = 803m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S5",
                            Price = 804m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Description = "Samsung phone description",
                            ImageUrl = "https://example.com/samsung.jpg",
                            Name = "Samsung Galaxy S6",
                            Price = 805m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 1",
                            Price = 1006m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 2",
                            Price = 1007m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 3",
                            Price = 1008m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 4",
                            Price = 1009m
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 5",
                            Price = 1010m
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            Description = "Apple phone description",
                            ImageUrl = "https://example.com/apple.jpg",
                            Name = "iPhone 6",
                            Price = 1011m
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 1",
                            Price = 312m
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 2",
                            Price = 313m
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 3",
                            Price = 314m
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 4",
                            Price = 315m
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 5",
                            Price = 316m
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 3,
                            Description = "Tecno phone description",
                            ImageUrl = "https://example.com/tecno.jpg",
                            Name = "Tecno Spark 6",
                            Price = 317m
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsAdmin = true,
                            PasswordHash = "100000.epkDlhQDSuyG76bjVBNXAA==.pXviqxKRvOWbCDkSY59AwDhKnsYBhnOBrdLqfz4bebg=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entites.Phone", b =>
                {
                    b.HasOne("DataAccessLayer.Entites.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
